services:
  reverse-proxy:
    image: traefik:v2.5
    container_name: main-reverse-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Map the static configuration into the container
      - ./traefik/static.yml:/etc/traefik/traefik.yml:ro
      # Map the dynamic configuration into the container
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      # Map the certificats into the container
      - ./letsencrypt:/letsencrypt
    command:
      - "--accesslog=true"
    networks:
      - mainlb_priv
      - apv_public


networks:
  apv_public:
    external: true
  mainlb_priv:
    name: mainlb_priv
    ipam:
      driver: default
      config:
      - subnet: 10.99.0.0/28